name: stratz_api
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1

dev_dependencies:
  freezed: ^0.14.2
  json_serializable: ^4.1.4
  build_runner: ^2.0.6  
  test: ^1.17.10
  mocktail: ^0.1.4
